import ContextualHOL.Evidence

open ContextualHOL

namespace ContextualHOL
namespace BasisDerivations

abbrev Arg := Evidence.Arg
abbrev Proof := Evidence.Proof

def betaSub2PointMem : Proof :=
  Evidence.Proof.basis BasisName.betaSub2Point [
    Evidence.Arg.ty "(X × Final)",
    Evidence.Arg.ty "X",
    Evidence.Arg.ty "X",
    Evidence.Arg.pred "elt",
    Evidence.Arg.term "(v0 X Final)",
    Evidence.Arg.term "(Cart.weakening X (X × Final) s)",
    Evidence.Arg.term "(pointAt X t)"
  ]

def betaV0PointMem : Proof :=
  Evidence.Proof.basis BasisName.betaV0PointArg1 [
    Evidence.Arg.ty "X",
    Evidence.Arg.ty "X",
    Evidence.Arg.pred "(curry X X PC elt)",
    Evidence.Arg.term "t",
    Evidence.Arg.term "(Final.term X ((Cart.weakening X (X × Final) s) ∘ pointAt X t))"
  ]

def betaWeakeningMem : Proof :=
  Evidence.Proof.basis BasisName.betaWeakeningArg2 [
    Evidence.Arg.ty "X",
    Evidence.Arg.ty "X",
    Evidence.Arg.ty "(X × Final)",
    Evidence.Arg.pred "(curry X X PC elt)",
    Evidence.Arg.term "t",
    Evidence.Arg.term "s",
    Evidence.Arg.term "(pointAt X t)"
  ]

def memBetaProof : Proof :=
  Evidence.Proof.iffTrans "_" "_" "_" betaSub2PointMem
    (Evidence.Proof.iffTrans "_" "_" "_" betaV0PointMem betaWeakeningMem)

def betaSub2PointMemRev : Proof :=
  Evidence.Proof.basis BasisName.betaSub2Point [
    Evidence.Arg.ty "(X × Final)",
    Evidence.Arg.ty "X",
    Evidence.Arg.ty "X",
    Evidence.Arg.pred "elt",
    Evidence.Arg.term "(Cart.weakening X (X × Final) z)",
    Evidence.Arg.term "(v0 X Final)",
    Evidence.Arg.term "(pointAt X t)"
  ]

def betaWeakeningMemRev : Proof :=
  Evidence.Proof.basis BasisName.betaWeakeningArg1 [
    Evidence.Arg.ty "X",
    Evidence.Arg.ty "X",
    Evidence.Arg.ty "(X × Final)",
    Evidence.Arg.pred "(curry X X PC elt)",
    Evidence.Arg.term "z",
    Evidence.Arg.term "(Final.term X ((v0 X Final) ∘ pointAt X t))",
    Evidence.Arg.term "(pointAt X t)"
  ]

def betaV0PointMemRev : Proof :=
  Evidence.Proof.basis BasisName.betaV0PointArg2 [
    Evidence.Arg.ty "X",
    Evidence.Arg.ty "X",
    Evidence.Arg.pred "(curry X X PC elt)",
    Evidence.Arg.term "z",
    Evidence.Arg.term "t"
  ]

def memBetaRevProof : Proof :=
  Evidence.Proof.iffTrans "_" "_" "_" betaSub2PointMemRev
    (Evidence.Proof.iffTrans "_" "_" "_" betaWeakeningMemRev betaV0PointMemRev)

def betaSub2PointConstAtom : Proof :=
  Evidence.Proof.basis BasisName.betaSub2Point [
    Evidence.Arg.ty "(X × Final)",
    Evidence.Arg.ty "X",
    Evidence.Arg.ty "X",
    Evidence.Arg.pred "elt",
    Evidence.Arg.term "(Cart.weakening X (X × Final) c)",
    Evidence.Arg.term "(Cart.weakening X (X × Final) d)",
    Evidence.Arg.term "(pointAt X t)"
  ]

def betaWeakeningConstAtomLeft : Proof :=
  Evidence.Proof.basis BasisName.betaWeakeningArg1 [
    Evidence.Arg.ty "X",
    Evidence.Arg.ty "X",
    Evidence.Arg.ty "(X × Final)",
    Evidence.Arg.pred "(curry X X PC elt)",
    Evidence.Arg.term "c",
    Evidence.Arg.term "(Final.term X ((Cart.weakening X (X × Final) d) ∘ pointAt X t))",
    Evidence.Arg.term "(pointAt X t)"
  ]

def betaWeakeningConstAtomRight : Proof :=
  Evidence.Proof.basis BasisName.betaWeakeningArg2 [
    Evidence.Arg.ty "X",
    Evidence.Arg.ty "X",
    Evidence.Arg.ty "(X × Final)",
    Evidence.Arg.pred "(curry X X PC elt)",
    Evidence.Arg.term "c",
    Evidence.Arg.term "d",
    Evidence.Arg.term "(pointAt X t)"
  ]

def constAtomBetaProof : Proof :=
  Evidence.Proof.iffTrans "_" "_" "_" betaSub2PointConstAtom
    (Evidence.Proof.iffTrans "_" "_" "_"
      betaWeakeningConstAtomLeft
      betaWeakeningConstAtomRight)

def renderGeneratedMemBeta : String :=
  "noncomputable def generated_memBeta (X : Type) (elt : Pred (X × X)) (t s : X) :\n" ++
  "  iff (Pred.term ((memAt X elt s) ∘ pointAt X t)) (curry X X PC elt t s) :=\n" ++
  "  " ++ memBetaProof.render ++ "\n"

def renderGeneratedMemBetaRev : String :=
  "noncomputable def generated_memBetaRev (X : Type) (elt : Pred (X × X)) (z t : X) :\n" ++
  "  iff (Pred.term\n" ++
  "        ((sub2 (X × Final) X X elt (Cart.weakening X (X × Final) z) (v0 X Final)) ∘ pointAt X t))\n" ++
  "      (curry X X PC elt z t) :=\n" ++
  "  " ++ memBetaRevProof.render ++ "\n"

def renderGeneratedConstAtomBeta : String :=
  "noncomputable def generated_constAtomBeta (X : Type) (elt : Pred (X × X)) (c d t : X) :\n" ++
  "  iff (Pred.term\n" ++
  "        ((sub2 (X × Final) X X elt (Cart.weakening X (X × Final) c) (Cart.weakening X (X × Final) d))\n" ++
  "          ∘ pointAt X t))\n" ++
  "      (curry X X PC elt c d) :=\n" ++
  "  " ++ constAtomBetaProof.render ++ "\n"

def generatedDerivationsFile : String :=
  "-- Generated by formalization/GenerateBasisDerivations.lean.\n" ++
  "-- This file is an M2 certificate target: proofs are rendered from Evidence.Proof.\n" ++
  "import definite_description\n\n" ++
  renderGeneratedMemBeta ++ "\n" ++
  renderGeneratedMemBetaRev ++ "\n" ++
  renderGeneratedConstAtomBeta

def regenCheckFile : String :=
  "-- Generated by formalization/GenerateBasisDerivations.lean.\n" ++
  "-- Ascribes generated proofs to the handwritten Core statement shapes.\n" ++
  "import definite_description\n" ++
  "import generated_basis_derivations\n\n" ++
  "noncomputable def memBeta_generated_check (X : Type) (elt : Pred (X × X)) (t s : X) :\n" ++
  "  iff (Pred.term ((memAt X elt s) ∘ pointAt X t)) (curry X X PC elt t s) :=\n" ++
  "  generated_memBeta X elt t s\n\n" ++
  "noncomputable def memBetaRev_generated_check (X : Type) (elt : Pred (X × X)) (z t : X) :\n" ++
  "  iff (Pred.term\n" ++
  "        ((sub2 (X × Final) X X elt (Cart.weakening X (X × Final) z) (v0 X Final)) ∘ pointAt X t))\n" ++
  "      (curry X X PC elt z t) :=\n" ++
  "  generated_memBetaRev X elt z t\n\n" ++
  "noncomputable def constAtomBeta_generated_check (X : Type) (elt : Pred (X × X)) (c d t : X) :\n" ++
  "  iff (Pred.term\n" ++
  "        ((sub2 (X × Final) X X elt (Cart.weakening X (X × Final) c) (Cart.weakening X (X × Final) d))\n" ++
  "          ∘ pointAt X t))\n" ++
  "      (curry X X PC elt c d) :=\n" ++
  "  generated_constAtomBeta X elt c d t\n\n" ++
  "#check @memBeta_generated_check\n" ++
  "#check @memBetaRev_generated_check\n" ++
  "#check @constAtomBeta_generated_check\n"

def ensureAllowed (proof : Proof) : IO Unit := do
  if proof.usesOnlyAllowed then
    pure ()
  else
    throw (IO.userError "generated proof references a name outside BasisName.all")

def main (_args : List String) : IO Unit := do
  ensureAllowed memBetaProof
  ensureAllowed memBetaRevProof
  ensureAllowed constAtomBetaProof
  IO.FS.writeFile "/home/andre/mathagent/ma1/generated_basis_derivations.cor"
    generatedDerivationsFile
  IO.FS.writeFile "/home/andre/mathagent/ma1/contextual_hol_basis_derivation_check.cor"
    regenCheckFile

end BasisDerivations
end ContextualHOL

def main (args : List String) : IO Unit :=
  ContextualHOL.BasisDerivations.main args
