name = "contextual_hol"
defaultTargets = ["ContextualHOL"]

[[require]]
name = "core-checker"
path = "../checker"

[[lean_lib]]
name = "ContextualHOL"

[[lean_exe]]
name = "generate_core_examples"
root = "GenerateCoreExamples"

[[lean_exe]]
name = "generate_basis_derivations"
root = "GenerateBasisDerivations"

[[lean_exe]]
name = "quote_set_theory"
root = "QuoteSetTheory"
